print("Begin18")
a = int(input("Sonlar o'qidagi A nuqtani kiritng=  "))
b = int(input("Endi B nuqtani kiriting = "))
c = int(input("C nuqtani kiritng = "))
print("AC va BC kesmalar uzunligining ko'paytmasi aniqlansin = " + str(int((c-a)*(b-c))))