print("Begin17")
a = int(input("Sonlar o'qidagi A nuqtani kiritng=  "))
b = int(input("Endi B nuqtani kiriting = "))
c = int(input("C nuqtani kiritng = "))
print("AC va BC kesmalarining uzunligini yig'indisini toping = " + str(int((c-a)+(c-b))))