print("Boolean 30")
a = int(input("A sonini kiriting = "))
b = int(input("B sonini kiriting = "))
c = int(input("C sonini kiriitng = "))
print("A, B, C uchburchak burchaklari")
print("Uchburchak teng tomonli = ", a==b and b==c)