print("Boolean 6")
a = int(input("A sonini kiriting = "))
b = int(input("B sonini kiriting = "))
c = int(input("C sonini kiriting = "))
print("Jumlani rostligini tekshiring (a<=b<=c) = ", a<=b and b<=c)