print("Boolean 7")
a = int(input("A sonini kiriting = "))
b = int(input("B sonini kiriting = "))
c = int(input("C sonini kiriting = "))
print("Jumlani rostligini tekshiring (B soni A va C sonlari orasida yotadi) = ", a>b and c>b)